on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: konekt.atwebpages.com
        username: 4011122_konekt
        password: ${{ secrets.FTP_PASS }}
        protocol: ftps
        server-dir: konekt.atwebpages.com/